### ISSUE TITLE
Enhance error handling with small read datasets

### ISSUE THREAD

**Issue by apetkau** [phac-nml/speciesabundance#14]
# Challenge

With very small read datasets (e.g., test files like the smaller read sets found in https://sairidapublic.blob.core.windows.net/downloads/data/irida-sample-data.zip), Kraken2 will report that no reads are found and trigger an error with the pipeline:

```
>> Checking report file: INXT_SAM_AYEEBXRY7G_kraken2_report.txt
Error: no reads found. Please check your Kraken report
```

# Possible cause

I believe this is caused by fastp removing all the reads from the test dataset, so there are no reads being passed to Kraken2.

# Suggested enhancement

One suggested enhancement would be to improve the error handling in this case. Instead of causing the entire pipeline to fail, the particular samples where this error occurred could be written to a `error_report.csv` file and the rest of the samples could continue to run through the pipeline as normal. This could be implemented similar to error handling in the `fetchdatairidanext` pipeline: https://github.com/phac-nml/fetchdatairidanext/pull/15

**Comment by kylacochrane** [comment]
This ERROR may not be associated with small read datasets but rather with a sample that contains no reads that match to the kraken2 database being used. This will result in a kraken2 report with all reads being assigned as **unclassified**.
This causes Bracken to outright fail. 

A new branch will be created to handle these errors, ignoring samples comprised of unclassified reads.
